---
- name: 
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/rafalgalan/Ansible_roles 
    git branch: main
  tasks:
  - name: Create /etc/ansible/roles directory
    file:
      path: /etc/ansible/roles
      state: directory
      mode: '0755'
    - name: Git checkout
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"